---

- name: Check OS
  assert:
    that:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"
    fail_msg: Host {{ ansible_hostname }} does not meet minimal reqs

- include_tasks: yum_gitlab.yml
  when:
    inventory_hostname == "gitlab"
  tags: [always]

- include_tasks: gitlab.yml
  when:
    inventory_hostname == "gitlab"
  tags: [always]

- include_tasks: yum_runner.yml
  when:
    inventory_hostname == "runner"
  tags: [always]

- include_tasks: runner.yml
  when:
    inventory_hostname == "runner"
  tags: [always]

- include_tasks: exporter.yml
  tags: [always]
