---

- name: Set timezone
  community.general.timezone:
    name: Europe/Moscow
  tags:
    - gitlab
    - pretasks

- name: Firewall - Disable SELinux
  become: true
  selinux:
    state: disabled
  tags:
    - gitlab
    - pretasks

- name: Firewall - Stop firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
  tags:
    - gitlab
    - pretasks

- name: Hosts - Rename Hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - gitlab
    - pretasks
