---
- name: Yum - Upgrade packages
  become: true
  ansible.builtin.yum:
    name: "*"
    enablerepo: base,updates,extras
    state: present
    update_cache: true
  tags:
    - gitlab
    - yum_runner

- name: Yum - Install packages
  become: true
  ansible.builtin.yum:
    name:
      - policycoreutils
      - postfix
      - python36
    state: present
  tags:
    - gitlab
    - yum_runner

- name: Yum - Get Git Runner repo
  ansible.builtin.get_url:
    url: "{{ runner_url }}"
    dest: "{{ tmp_path }}/script.rpm.sh"
    mode: '0755'
  tags:
    - gitlab
    - yum_runner

- name: Yum - Install Git Runner repo
  become: true
  ansible.builtin.command: "{{ tmp_path }}/script.rpm.sh"
  tags:
    - gitlab
    - yum_runner

- name: Yum - Install GitLab Runner
  become: true
  ansible.builtin.yum:
    name:
      - gitlab-runner
    state: present
  tags:
    - gitlab
    - yum_runner
...
